名字: 建筑
在:
  workflow_dispatch:
输入:
        package_name:
描述: “游戏包名称：”
必需: 真正的

工作:
建筑:
    runs-on: ubuntu-latest
步骤:
    - 用途: actions/checkout@v4
    - 用途: actions/setup-java@v4
与:
分布: 穆林
        java-version: 11
我-我-我: 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g'
我-我-我: |
"s/com.game.packagename/${{ github.event.inputs.package_name }}/g"'chmod+x./gradlewyou
./gradlew:模块你喜欢吗
G拉德勒 module/src/main/cpp/game.h
跑
    - 用途将权限添加到./gradlewyousyou you：'chmod+x./gradlewyou: actions/upload-artifact@v4
与:
名字: zygisk-il2cppdumper
路径: out/magisk_module_release/
